/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_yanbober_ndkapplication_NdkJniUtils */

#ifndef _Included_my_example_myjnidemo_JniUtils
#define _Included_my_example_myjnidemo_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     my_example_myjnidemo_JniUtils
 * Method:    getTestString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_my_example_myjnidemo_JniUtils_getTestString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif